### PR TITLE
fix!: address all gRPC deprecations

### LINKED ISSUE #13: StreamDirector definition in README.md is probably outdated
I was taking a look at the README.md and the tests. It seems the references of `StreamDirector` in README.md are no longer up to date.

### PR DESCRIPTION
**Pull request by maxbrunet**
This addresses all deprecation warnings from `grpc-go` in tests and examples (e.g. use `NewClient` instead of `DialContext`, the context from `DialContext` was only useful if the [`grpc.WithBlock()`] option was used, this is also deprecated)

The only exceptions is the change in `proxy/codec.go` to implement `encoding.Codec` instead `grpc.Codec` which is a breaking change.

The clients must now use `grpc.NewClient` with the `grpc.WithDefaultCallOptions(grpc.ForceCodec(proxy.Codec()))` option. And servers must now use `grpc.NewServer` `encoding.RegisterCodec(proxy.Codec())` `grpc.ForceServerCodec(proxy.Codec())` option.

Happy to look into a solution without breaking change if it is not acceptable :)

Closes #13

[`grpc.WithBlock()`]: https://pkg.go.dev/google.golang.org/grpc#WithBlock

### CODE REVIEW

File: proxy/handler_one2many_test.go [hunk 1]
```diff
@@ -628,8 +621,9 @@ func (s *ProxyOne2ManySuite) SetupSuite() {
 		return proxy.One2Many, result, nil
 	}
 
+	encoding.RegisterCodec(proxy.Codec())
```
Comment (DmitriyMV) [inline proxy/handler_one2many_test.go]: Grpc docs [recommends](https://github.com/grpc/grpc-go/blob/master/Documentation/encoding.md) to register codecs in the package which defines the codec.

Comment (maxbrunet) [reply proxy/handler_one2many_test.go]: Since the name is `proto`, not sure if it is desirable, I would leave the control to the user, maybe they just mean to create a new `CodecWithParent` rather than registering. With `init`, it could cause trouble with import ordering regarding which codec gets to override the `proto` one

Another codec that does similar and does not use `init` either is `vtprotobuf`:

https://github.com/planetscale/vtprotobuf/blob/v0.6.0/codec/grpc/grpc_codec.go

But if you insist I will do it, let me know

File: proxy/codec.go [hunk 2]
```diff
@@ -61,8 +55,8 @@ func (c *rawCodec) Unmarshal(data []byte, v interface{}) error {
 	return nil
 }
 
-func (c *rawCodec) String() string {
-	return fmt.Sprintf("proxy>%s", c.parentCodec.String())
+func (c *rawCodec) Name() string {
+	return c.parentCodec.Name()
```
Comment (DmitriyMV) [inline proxy/codec.go]: I think we should preserve the "proxy->%s" naming here.

File: proxy/examples_test.go [hunk 3]
```diff
@@ -19,8 +22,10 @@ var director proxy.StreamDirector
 
 // ExampleRegisterService is a simple example of registering a service with the proxy.
 func ExampleRegisterService() {
+	encoding.RegisterCodec(proxy.Codec())
```
Comment (DmitriyMV) [inline proxy/examples_test.go]: On further investigation I believe we can remove this call, since we require callers to explicitly set our codec. AKA we don't want to override the default one. And both server and client created with `grpc.Force*` call should do the trick.

File: proxy/examples_test.go [hunk 4]
```diff
@@ -19,8 +22,10 @@ var director proxy.StreamDirector
...
+
 	// A gRPC server with the proxying codec enabled.
-	server := grpc.NewServer(grpc.CustomCodec(proxy.Codec())) //nolint: staticcheck
+	server := grpc.NewServer()
```
Comment (DmitriyMV) [inline proxy/examples_test.go]: Passing `grpc.ForceServerCodec(proxy.Codec())` should do the trick.

File: proxy/examples_test.go [hunk 5]
```diff
@@ -34,29 +39,48 @@ func ExampleRegisterService() {
 
 // ExampleTransparentHandler is an example of redirecting all requests to the proxy.
 func ExampleTransparentHandler() {
+	encoding.RegisterCodec(proxy.Codec())
+
 	grpc.NewServer(
-		grpc.CustomCodec(proxy.Codec()), //nolint: staticcheck
-		grpc.UnknownServiceHandler(proxy.TransparentHandler(director)))
+		grpc.UnknownServiceHandler(proxy.TransparentHandler(director)),
```
Comment (DmitriyMV) [inline proxy/examples_test.go:41]: Passing grpc.ForceServerCodec(proxy.Codec()) should do the trick.

File: proxy/handler_one2many_test.go [hunk 6]
```diff
@@ -628,8 +621,9 @@ func (s *ProxyOne2ManySuite) SetupSuite() {
...
+
 	s.proxy = grpc.NewServer(
-		grpc.CustomCodec(proxy.Codec()), //nolint: staticcheck
 		grpc.UnknownServiceHandler(proxy.TransparentHandler(director)),
```
Comment (DmitriyMV) [inline proxy/handler_one2many_test.go:625]: Passing grpc.ForceServerCodec(proxy.Codec()) should do the trick.

File: proxy/handler_one2one_test.go [hunk 7]
```diff
@@ -250,8 +255,9 @@ func (s *ProxyOne2OneSuite) SetupSuite() {
 		}, nil
 	}
 
+	encoding.RegisterCodec(proxy.Codec())
+
 	s.proxy = grpc.NewServer(
-		grpc.CustomCodec(proxy.Codec()), //nolint: staticcheck
 		grpc.UnknownServiceHandler(proxy.TransparentHandler(director)),
```
Comment (DmitriyMV) [inline proxy/handler_one2one_test.go:259]: Passing grpc.ForceServerCodec(proxy.Codec()) should do the trick.

**Review by DmitriyMV — CHANGES_REQUESTED** [review]
I think we can remove `encoding.RegisterCodec(proxy.Codec())` entirely.

File: proxy/handler_one2many_test.go (hunk 1 above)
Comment (DmitriyMV) [reply proxy/handler_one2many_test.go]: See my other comments.

File: proxy/examples_test.go (hunk 3 above)
Comment (maxbrunet) [reply proxy/examples_test.go]: Nice find for `grpc.ForceServerCodec`! Not a fan of the global state either

File: proxy/codec.go (hunk 2 above)
Comment (maxbrunet) [reply proxy/codec.go]: Just a note, this will not allow it to be used as a regular codec:

> When specified in either of these ways, messages will be encoded using this codec and sent along with headers indicating the codec (`content-type` set to `application/grpc+<codec name>`). 

https://github.com/grpc/grpc-go/blob/v1.65.0/Documentation/encoding.md#using-a-codec

**Review by DmitriyMV — APPROVED** [review]

**Comment by DmitriyMV** [comment]
Updated the commit and commit/PR message.

**Review by DmitriyMV — APPROVED** [review]

**Comment by DmitriyMV** [comment]
@maxbrunet congrats this is now merged.

**Comment by maxbrunet** [comment]
Thank you @DmitriyMV! Any chance you could tag a release, please?

**Comment by DmitriyMV** [comment]
@maxbrunet https://github.com/siderolabs/grpc-proxy/releases/tag/v0.4.1
